package com.mycompany.ProyectoII.vista;

import com.mycompany.ProyectoII.Administrativo;
import com.mycompany.ProyectoII.Farmaceuta;
import com.mycompany.ProyectoII.Medico;
import com.mycompany.ProyectoII.Persona;
import com.mycompany.ProyectoII.control.Control;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.kordamp.ikonli.fontawesome.FontAwesome;
import org.kordamp.ikonli.swing.FontIcon;

/* -------------------------------------------------------------------+
*                                                                     |
* (c) 2025                                                            |
* EIF206 - Programación 3                                             |
* 2do ciclo 2025                                                      |
* NRC 51189 – Grupo 05                                                |
* Proyecto 2                                                          |
*                                                                     |
* 2-0816-0954; Avilés López, Karen Minards                            |
* 4-0232-0641; Zárate Hernández, Nicolas Alfredo                      |
*                                                                     |
* versión 2.0.0 06-11-2025                                            |
*                                                                     |
* --------------------------------------------------------------------+
*/

public class CambioContraseña extends javax.swing.JFrame {

    public CambioContraseña(Control ControlPrincipal) {
        this.controlador = ControlPrincipal;
        initComponents();
        init();
        this.setLocationRelativeTo(null);
    }

    private void init() {
        configuracionIconosBotones();
    }

    public void configuracionIconosBotones() {
        // Tamaño deseado para los iconos
        int tamañoIcono = 20; // 24px es un tamaño estándar

        // Botón Login
        btnCambiar.setIcon(FontIcon.of(FontAwesome.CHECK, tamañoIcono)); // icono de llave
        btnCambiar.setHorizontalTextPosition(SwingConstants.RIGHT);
        btnCambiar.setVerticalTextPosition(SwingConstants.CENTER);
        btnCambiar.setIconTextGap(8);
        btnCambiar.setHorizontalAlignment(SwingConstants.LEFT);

        // Botón Change Password
        btnRegresar.setIcon(FontIcon.of(FontAwesome.ARROW_LEFT, tamañoIcono)); // icono de engranaje
        btnRegresar.setHorizontalTextPosition(SwingConstants.RIGHT);
        btnRegresar.setVerticalTextPosition(SwingConstants.CENTER);
        btnRegresar.setIconTextGap(8);
        btnRegresar.setHorizontalAlignment(SwingConstants.LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Cedula = new javax.swing.JLabel();
        Clave = new javax.swing.JLabel();
        txtclaveAnterior = new javax.swing.JPasswordField();
        txtCedula = new javax.swing.JTextField();
        btnCambiar = new javax.swing.JButton();
        Clave1 = new javax.swing.JLabel();
        txtclaveNueva = new javax.swing.JPasswordField();
        lblmensaje = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cambio Contraseña");
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Cedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cedula.setText("Cedula: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(132, 120, 0, 0);
        getContentPane().add(Cedula, gridBagConstraints);

        Clave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clave.setText("Clave Anterior: ");
        Clave.setAlignmentX(0.25F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 120, 0, 0);
        getContentPane().add(Clave, gridBagConstraints);

        txtclaveAnterior.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtclaveAnterior.setPreferredSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 120);
        getContentPane().add(txtclaveAnterior, gridBagConstraints);

        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setPreferredSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(131, 1, 0, 120);
        getContentPane().add(txtCedula, gridBagConstraints);

        btnCambiar.setText("Cambiar");
        btnCambiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCambiar.setMargin(new java.awt.Insets(2, 19, 3, 14));
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 1, 115, 0);
        getContentPane().add(btnCambiar, gridBagConstraints);

        Clave1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clave1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clave1.setText("Clave Nueva: ");
        Clave1.setAlignmentX(0.25F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 120, 0, 0);
        getContentPane().add(Clave1, gridBagConstraints);

        txtclaveNueva.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtclaveNueva.setPreferredSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 120);
        getContentPane().add(txtclaveNueva, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(lblmensaje, gridBagConstraints);

        btnRegresar.setText("Regresar");
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setMargin(new java.awt.Insets(2, 19, 3, 14));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 39, 115, 0);
        getContentPane().add(btnRegresar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
String cedula = txtCedula.getText().trim();
    String claveAnterior = new String(txtclaveAnterior.getPassword());
    String nuevaClave = new String(txtclaveNueva.getPassword());

    if (cedula.isEmpty() || claveAnterior.isEmpty() || nuevaClave.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
        return;
    }

    try {
        Persona persona = controlador.validarUsuario(cedula, claveAnterior);

        if (persona == null) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
            return;
        }

        if (nuevaClave.equals(persona.getClave())) {
            JOptionPane.showMessageDialog(this, "La nueva clave no puede ser igual a la anterior");
            return;
        }

        boolean actualizado = false;

        if (persona instanceof Medico) {
            
            actualizado = controlador.actualizarClaveMedico(cedula, nuevaClave);
        } else if (persona instanceof Farmaceuta) {
            actualizado = controlador.actualizarClaveFarma(cedula, nuevaClave);
        } else if (persona instanceof Administrativo) {
            actualizado = controlador.actualizarClaveAdmi(cedula, nuevaClave);
        }

        if (actualizado) {
            JOptionPane.showMessageDialog(this, "Contraseña cambiada con éxito");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar la contraseña. Intente nuevamente.");
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error de base de datos: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // Abrir la ventana de Login
        this.dispose();
       controlador.volverVentanaPrincipal();

    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CambioContraseña(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Clave1;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtclaveAnterior;
    private javax.swing.JPasswordField txtclaveNueva;
    // End of variables declaration//GEN-END:variables

    private final Control controlador;
}
